"""The authored half of the calibration query set (RESULTS.md §5).

The benchmark supplies real questions against a real corpus, but its corpus is
encyclopedic -- 455 pre-stated facts about sports, birthplaces and universities. The
gate will actually run against a *conversational* session holding a dozen facts about
one user, and the score distribution depends on the corpus, not only on the model. So
the calibration measures both regimes and only trusts a floor that survives both.

This module is the conversational one. The queries are authored, and that is stated
plainly wherever the numbers are reported: there is no public corpus of "gateway turns
against a personal memory store". What keeps it honest is the negative set -- these are
the turns a real session is full of (chit-chat, coding questions, meta-requests), and
several sit deliberately close to the stored facts ("should I use tabs or spaces?"
against a store that holds an editor preference) so the floor is not chosen against
straw negatives.

The FACTS are no longer authored. They are generated by `bench.gen_calib_fixtures`,
which runs the real `OllamaExtractor` over authored learn-turns and keeps what it emits.
Hand-writing them is what produced RESULTS.md §12's defect: the authored facts were terse
fragments ("deploys to staging by default") where P1 actually stores third-person
sentences ("the user deploys to staging by default"), and the authored positives shared
word stems with them, so the BM25 deduction that dominates real gate behaviour almost
never fired during the run that chose `score_floor = 0.48`. Do not edit the two generated
literals by hand -- change the turns in the generator and re-run it, then re-run
`bench.calibrate`, because the fixtures, the embedder and the floor are one chain.
"""

from __future__ import annotations

# (fact, subject_hint, attribute) -- exactly what P1 emitted, verbatim. GENERATED by
# `bench.gen_calib_fixtures`; see the module docstring before editing.
CHAT_FACTS: list[tuple[str, str, str]] = [
    ('the user deploys to staging by default', 'the user', 'default deployment target'),
    ('the user prefers Python for backend work', 'the user', 'preferred backend language'),
    ('the user is based in Amsterdam', 'the user', 'location'),
    ('the user uses Neovim as their editor', 'the user', 'text editor'),
    ('the user runs tests with pytest', 'the user', 'test runner'),
    ('the user has a dog named Pixel', 'the user', 'pet name'),
    ('the user works at a company called Northgate', 'the user', 'employer'),
    ('the user prefers dark mode in the terminal', 'the user', 'terminal theme'),
    ('the user is allergic to peanuts', 'the user', 'allergies'),
    ('the user drinks oat milk in their coffee', 'the user', 'coffee preference'),
    ('the user manages a team of six engineers', 'the user', 'team size'),
    ('the user travels to Lisbon every quarter for work', 'the user', 'work travel schedule'),
]

# (query, index into CHAT_FACTS the gate should surface). Deliberately phrased as turns
# rather than as the fact restated -- a query that echoes the fact's wording measures
# string overlap, not recall.
CHAT_POSITIVES: list[tuple[str, int]] = [
    ("what's my deploy setup?", 0),
    ("where do I deploy again?", 0),
    ("what's my default deploy target?", 0),
    ("which language should I use for the backend?", 1),
    ("remind me which language I prefer", 1),
    ("what city am I in?", 2),
    ("where do I live?", 2),
    ("which editor do I use?", 3),
    ("what's my editor setup?", 3),
    ("how do I run the tests?", 4),
    ("which test framework do I run?", 4),
    # recall-poc-spec.md §6 uses this turn to show the *write* path storing nothing
    # (transient, no durable fact). That says nothing about the read path: the store does
    # hold the test runner, and surfacing it here is a correct recall, not a false open.
    # It was labelled a negative in the first calibration run and was the single largest
    # false-open for all three models -- a mislabel, corrected here rather than left to
    # flatter the numbers.
    ("run the tests again", 4),
    ("what's my dog called?", 5),
    ("tell me about my dog", 5),
    ("who do I work for?", 6),
    ("what company do I work at?", 6),
    ("do I prefer light or dark mode?", 7),
    ("any food allergies I should know about?", 8),
    ("am I allergic to anything?", 8),
    ("what do I take in my coffee?", 9),
    ("what kind of milk do I use?", 9),
    ("how big is my team?", 10),
    ("how many engineers report to me?", 10),
    # Reworded with the fact: P1 refuses a dated itinerary as transient, so the stored
    # fact is a recurring trip rather than a flight on the 14th.
    ("how often do I go to Lisbon?", 11),
    ("what are my travel plans?", 11),
    # --- PARAPHRASE-ONLY positives: the case RESULTS.md §12 is about --------------
    #
    # Every positive above shares a word stem with its fact ("deploy setup"/"deploys",
    # "test framework"/"tests", "milk"/"oat milk"), so the BM25 arm finds something on
    # every one of them and the 1/(1+w) deduction almost never bites. That is the same
    # blind spot the facts had before they were generated from the real extractor, one
    # level up: a fixture that cannot express the failure cannot calibrate against it.
    #
    # These ask the same questions with NO content word in common with the stored fact --
    # "what am i called" against "the user's name is Bart", which is the shape the gate
    # was reported failing on. They are the honest hard case for recall, and they are
    # labelled separately so their contribution is visible rather than averaged away.
    ("where does my code end up when I ship?", 0),
    ("what should I write the server in?", 1),
    ("which city do I call home?", 2),
    ("what do I type into all day?", 3),
    ("how do I check nothing is broken?", 4),
    ("what's my pet called?", 5),
    ("who employs me?", 6),
    ("is my shell bright or dim?", 7),
    ("anything I can't eat?", 8),
    ("what goes in my flat white?", 9),
    ("how many people report to me?", 10),
    ("do I go abroad for work often?", 11),
]

# Turns where the gate must stay shut: the store has nothing that answers them. Mixed
# deliberately -- pure off-domain chit-chat, plus a tail of near-misses that share the
# store's register ("what's on my calendar today?", "should I use tabs or spaces?").
OFF_DOMAIN_NEGATIVES: list[str] = [
    "what's the weather in Paris?",
    "how do I center a div in CSS?",
    "explain the difference between TCP and UDP",
    "write me a haiku about autumn",
    "what time is it in Tokyo?",
    "summarize this article for me",
    "can you explain that again?",
    "thanks, that helps",
    "what's 17 times 23?",
    "translate 'good morning' into Japanese",
    "give me a recipe for banana bread",
    "what does HTTP 429 mean?",
    "how long should I boil an egg?",
    "draft an email declining a meeting",
    "explain recursion like I'm five",
    "is it going to rain tomorrow?",
    "set a timer for 10 minutes",
    "help me debug this stack trace",
    "how do I revert a git commit?",
    "what are the side effects of ibuprofen?",
    "recommend a sci-fi novel",
    "convert 200 pounds to kilograms",
    "what's the difference between a list and a tuple?",
    "how many calories are in an avocado?",
    "explain quantum entanglement briefly",
    "why is the sky blue?",
    "what's a good name for a startup?",
    "tell me a joke",
    "what does this error mean: ECONNREFUSED",
    "how far away is the moon?",
    "write a SQL query joining two tables",
    "open the file and show me line 40",
    "what's on my calendar today?",
    "should I use tabs or spaces?",
    "which of these two designs looks better?",
    "book a table for two at 8pm",
    "remind me to call the dentist",
    "what's the best way to learn guitar?",
    "can you rewrite that paragraph more concisely?",
]


# --- a conversational session whose subjects COMPETE --------------------------------
#
# `CHAT_FACTS` above holds one fact per subject with no two subjects sharing a relation,
# which is a real shape (a short session) but a lucky one: the wrong-subject failure
# cannot occur there, so it cannot measure the defence against it either. A session that
# runs for any length of time accumulates competing subjects -- two services with deploy
# targets, two teams with leads, two pets with breeds -- and that is exactly the shape
# where similarity alone starts answering questions about the wrong entity.
#
# This fixture is that shape, and unlike `CHAT_FACTS` it carries HARD negatives: queries
# in a relation the store holds, about an entity it does not.
CROWDED_CHAT_FACTS: list[tuple[str, str, str]] = [
    ('the web app deploys to staging', 'the web app', 'deployment target'),
    ('the api deploys to prod', 'the api', 'deployment target'),
    ('the docs site deploys to Netlify', 'the docs site', 'deployment platform'),
    ("the user's work laptop runs Linux", "the user's work laptop", 'operating system'),
    ("the user's home desktop runs Windows", "the user's home desktop", 'operating system'),
    ('Pixel is a border collie', 'Pixel', 'breed'),
    ('Mochi is a Siamese cat', 'Mochi', 'breed'),
    ('Sarah leads the platform team', 'Sarah', 'role'),
    ('Tom leads the data team', 'Tom', 'role'),
    ('the platform team has six engineers', 'the platform team', 'team size'),
    ('the data team has four engineers', 'the data team', 'size'),
    ('the staging cluster is in eu-west-1', 'the staging cluster', 'location'),
    ('the production cluster is located in us-east-1', 'the production cluster', 'location'),
]

CROWDED_CHAT_POSITIVES: list[tuple[str, int]] = [
    ("where does the web app deploy?", 0),
    ("what's the deploy target for the api?", 1),
    ("where does the docs site go?", 2),
    ("what OS is on the work laptop?", 3),
    ("what does the home desktop run?", 4),
    ("what breed is Pixel?", 5),
    ("what kind of cat is Mochi?", 6),
    ("who leads the platform team?", 7),
    ("who runs the data team?", 8),
    ("how big is the platform team?", 9),
    ("how many engineers are on the data team?", 10),
    ("which region is the staging cluster in?", 11),
    ("where is the prod cluster hosted?", 12),
]

# Same relations, entities the store has never heard of. Under similarity alone these
# match a sibling fact almost perfectly.
CROWDED_CHAT_HARD_NEGATIVES: list[str] = [
    "where does the mobile app deploy?",
    "what's the deploy target for the admin panel?",
    "where does the scheduler deploy?",
    "what OS does the media server run?",
    "what does the tablet run?",
    "what breed is Luna?",
    "what kind of dog is Biscuit?",
    "who leads the design team?",
    "who runs the QA team?",
    "how big is the security team?",
    "how many engineers are on the mobile team?",
    "which region is the dev cluster in?",
    "where is the analytics cluster hosted?",
]
